### ISSUE TITLE
Unable to Run "akamai cps <command>"

### ISSUE THREAD

**Issue by KyL0R3Nz0** [akamai/cli-cps#32]
No matter what I do, I get an error when attempting to use cli-cps.

Executing `akamai cps setup` or `akamai cps list` or anything results in:

```
Traceback (most recent call last):
  File "/home/vicel005/.akamai-cli/src/cli-cps/bin/akamai-cps", line 20, in <module>
    from cps import cli
  File "/home/vicel005/.akamai-cli/src/cli-cps/bin/cps.py", line 33, in <module>
    from prettytable import PrettyTable
ModuleNotFoundError: No module named 'prettytable'
```

I also tried installing the cli-cps module under root, and get the same things:
```
Traceback (most recent call last):
  File "/root/.akamai-cli/src/cli-cps/bin/akamai-cps", line 20, in <module>
    from cps import cli
  File "/root/.akamai-cli/src/cli-cps/bin/cps.py", line 33, in <module>
    from prettytable import PrettyTable
ModuleNotFoundError: No module named 'prettytable'
```

**Comment by KyL0R3Nz0** [comment]
This might be a Python2 vs Python3 issue.

Rather than delete my issue and hide my face in embarrassment, I will install Python 3.7 and see if this works again. 

I will come back to comment once I have done that.

**Comment by KyL0R3Nz0** [comment]
That was it. It didn't like Python 2.7.
