### ISSUE TITLE
Error using retrieve-enrollment --enrollment-id

### ISSUE THREAD

**Issue by javiergarza** [akamai/cli-cps#4]
seems there is an issue using retrieve-enrollment --enrollment-id

As you can see:
```
akamai cps list
+---------------+------------------------------------+------------------+---------------+-----------------------+
| Enrollment ID | Common Name (SAN Count)            | Certificate Type | *In-Progress* | Test on Staging First |
+---------------+------------------------------------+------------------+---------------+-----------------------+
| *60325*       | mjm-akamai.iwishtechdemoswere.cool | dv san           | *Yes*         | No                    |
+---------------+------------------------------------+------------------+---------------+-----------------------+
```

This fails
```
akamai cps retrieve-enrollment --enrollment-id 60325 
Traceback (most recent call last):
  File "/Users/jgarza/.akamai-cli/src/cli-cps/bin/akamai-cps", line 1293, in <module>
    status = cli()
  File "/Users/jgarza/.akamai-cli/src/cli-cps/bin/akamai-cps", line 222, in cli
    return getattr(sys.modules[__name__], args.command.replace("-", "_"))(args)
  File "/Users/jgarza/.akamai-cli/src/cli-cps/bin/akamai-cps", line 1156, in retrieve_enrollment
    ' with enrollment-id: ' + str(enrollmentId))
TypeError: must be str, not NoneType
```

But requesting cn works
```
akamai cps retrieve-enrollment --cn mjm-akamai.iwishtechdemoswere.cool
Getting details for mjm-akamai.iwishtechdemoswere.cool with enrollment-id: 60325
{
    "location": "/cps/v2/enrollments/60325",
    "ra": "lets-encrypt",
...
```

**Comment by vreddhi** [comment]
The bug is verified, and the fix will be out in 2-3 days.

**Comment by amrraj** [comment]
I encountered the same error when running the audit command.

**Comment by vreddhi** [comment]
Issue is now fixed and verified. https://github.com/akamai/cli-cps/releases/tag/v0.1.3
