### ISSUE TITLE
Unable to Install or Use CPS package.

### ISSUE THREAD

**Issue by lv-labwerks** [akamai/cli-cps#46]
This step took about 15 seconds:
```
$ akamai install property
Attempting to fetch command from https://github.com/akamai/cli-property.git... ... [OK]
Installing... ... [OK]
```

This part I let run about about an hour, and it never finished:
```
$ akamai install cps
Attempting to fetch command from https://github.com/akamai/cli-cps.git... ... [OK]
Installing... [==========]
```

When trying to run akamai cps list, I get this error
```
$ akamai cps list
Traceback (most recent call last):
  File "/home/<user>/.akamai-cli/src/cli-cps/bin/akamai-cps", line 20, in <module>
    from cps import cli
  File "/home/<user>/.akamai-cli/src/cli-cps/bin/cps.py", line 31, in <module>
    from akamai.edgegrid import EdgeGridAuth, EdgeRc
ModuleNotFoundError: No module named 'akamai'
```

**Comment by robertolopezlopez** [comment]
@LorenzoVicente : please try once again with latest CLI release.
