### ISSUE TITLE
improving the installation experience on python2

### ISSUE THREAD

**Issue by javiergarza** [akamai/cli-cps#7]
We should improve the installation experience for people on python 2.

```
$ akamai uninstall cps
Attempting to uninstall "cps" command...... [OK]

$ pyenv shell 2.7.10
$ akamai install cps
Attempting to fetch command from https://github.com/akamai/cli-cps.git...... [OK]
Installing.... panic: runtime error: index out of range

goroutine 1 [running]:
main.installPython(0xc4200cee40, 0x25, 0xc42009d000, 0x1, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/private/tmp/akamai-20180507-18048-1kotjwh/cli-1.0.2/src/github.com/akamai/cli/package_python.go:42 +0x6c6
main.installPackageDependencies(0xc4200cee40, 0x25, 0x0, 0xc42017ac01)
	/private/tmp/akamai-20180507-18048-1kotjwh/cli-1.0.2/src/github.com/akamai/cli/command_install.go:128 +0xc56
main.installPackage(0xc4200cee10, 0x25, 0x0, 0x0, 0xc420183a88)
	/private/tmp/akamai-20180507-18048-1kotjwh/cli-1.0.2/src/github.com/akamai/cli/command_install.go:98 +0x5d1
main.cmdInstall(0xc4200d8dc0, 0x0, 0xc4200d8dc0)
	/private/tmp/akamai-20180507-18048-1kotjwh/cli-1.0.2/src/github.com/akamai/cli/command_install.go:39 +0x145
github.com/akamai/cli/vendor/github.com/urfave/cli.HandleAction(0x14fa640, 0x15e0298, 0xc4200d8dc0, 0xc4200d4500, 0x0)
	/private/tmp/akamai-20180507-18048-1kotjwh/cli-1.0.2/src/github.com/akamai/cli/vendor/github.com/urfave/cli/app.go:490 +0xc8
github.com/akamai/cli/vendor/github.com/urfave/cli.Command.Run(0x15bea9e, 0x7, 0x0, 0x0, 0xc4201785b0, 0x1, 0x1, 0x0, 0x0, 0x15db32f, ...)
	/private/tmp/akamai-20180507-18048-1kotjwh/cli-1.0.2/src/github.com/akamai/cli/vendor/github.com/urfave/cli/command.go:210 +0xa36
github.com/akamai/cli/vendor/github.com/urfave/cli.(*App).Run(0xc4200cb6c0, 0xc4200b81b0, 0x3, 0x3, 0x0, 0x0)
	/private/tmp/akamai-20180507-18048-1kotjwh/cli-1.0.2/src/github.com/akamai/cli/vendor/github.com/urfave/cli/app.go:255 +0x6a0
main.main()
	/private/tmp/akamai-20180507-18048-1kotjwh/cli-1.0.2/src/github.com/akamai/cli/akamai.go:43 +0xa1
```

Installation works fine on 3.6.5
```
$ akamai uninstall cps
Attempting to uninstall "cps" command...... [OK]
$ pyenv shell 3.6.5
$ akamai install cps
Attempting to fetch command from https://github.com/akamai/cli-cps.git...... [OK]
Installing...... [OK]

Installed Commands:

  auth
    Interface for Akamai Edgegrid Authentication
  config
    Manage configuration
  cps (alias: certs)
    Access Certificate Provisioning System (CPS) Information
  help
    Displays help information
  imaging (alias: img)
    An Akamai CLI package for Image Manager
  install (alias: get)
    Fetch and install packages from a Git repository.
  list
    Displays available commands
  promotional-deployment (aliases: pd, prodeploy)
    Promotional deployment for DevOps
  property
    Manage configurations for Akamai properties
  search
    Search for packages in the official Akamai CLI package repository
  uninstall
    Uninstall package containing <command>
  update
    Update one or more commands. If no command is specified, all commands are updated

See "akamai help [command]" for details.
```

**Comment by vreddhi** [comment]
The pre-requisite is python 3+. This is mentioned in README, as well as requirements.txt

**Comment by javiergarza** [comment]
OK, will do

**Comment by javiergarza** [comment]
@dshafik do you agree this is something that needs to be done at he cli package level?

**Comment by dshafik** [comment]
@javiergarza this is a bug in akamai/cli, yes.

**Comment by aetsai** [comment]
python2 eol in 2020, closing this
